/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegsiterRouteImport } from './routes/regsiter'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookRouteImport } from './routes/book'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as SuperadminSecurityRouteImport } from './routes/superadmin.security'
import { Route as SuperadminRolesRouteImport } from './routes/superadmin.roles'
import { Route as SuperadminAuditRouteImport } from './routes/superadmin.audit'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as AuthTwoFactorRouteImport } from './routes/auth.two-factor'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminWorkshopRouteImport } from './routes/admin.workshop'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegsiterRoute = RegsiterRouteImport.update({
  id: '/regsiter',
  path: '/regsiter',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackRoute,
} as any)
const SuperadminSecurityRoute = SuperadminSecurityRouteImport.update({
  id: '/superadmin/security',
  path: '/superadmin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRolesRoute = SuperadminRolesRouteImport.update({
  id: '/superadmin/roles',
  path: '/superadmin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminAuditRoute = SuperadminAuditRouteImport.update({
  id: '/superadmin/audit',
  path: '/superadmin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkshopRoute = AdminWorkshopRouteImport.update({
  id: '/admin/workshop',
  path: '/admin/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/admin/chats',
  path: '/admin/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regsiter': typeof RegsiterRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/track/$id': typeof TrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regsiter': typeof RegsiterRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/track/$id': typeof TrackIdRoute
  '/admin': typeof AdminIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regsiter': typeof RegsiterRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/track/$id': typeof TrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/book'
    | '/bookings'
    | '/chat'
    | '/contact'
    | '/login'
    | '/loyalty'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/regsiter'
    | '/services'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workshop'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/two-factor'
    | '/invoice/$id'
    | '/superadmin/audit'
    | '/superadmin/roles'
    | '/superadmin/security'
    | '/track/$id'
    | '/admin/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/book'
    | '/bookings'
    | '/chat'
    | '/contact'
    | '/login'
    | '/loyalty'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/regsiter'
    | '/services'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workshop'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/two-factor'
    | '/invoice/$id'
    | '/superadmin/audit'
    | '/superadmin/roles'
    | '/superadmin/security'
    | '/track/$id'
    | '/admin'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/book'
    | '/bookings'
    | '/chat'
    | '/contact'
    | '/login'
    | '/loyalty'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/regsiter'
    | '/services'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workshop'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/two-factor'
    | '/invoice/$id'
    | '/superadmin/audit'
    | '/superadmin/roles'
    | '/superadmin/security'
    | '/track/$id'
    | '/admin/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegsiterRoute: typeof RegsiterRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWorkshopRoute: typeof AdminWorkshopRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  SuperadminAuditRoute: typeof SuperadminAuditRoute
  SuperadminRolesRoute: typeof SuperadminRolesRoute
  SuperadminSecurityRoute: typeof SuperadminSecurityRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regsiter': {
      id: '/regsiter'
      path: '/regsiter'
      fullPath: '/regsiter'
      preLoaderRoute: typeof RegsiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/superadmin/security': {
      id: '/superadmin/security'
      path: '/superadmin/security'
      fullPath: '/superadmin/security'
      preLoaderRoute: typeof SuperadminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/roles': {
      id: '/superadmin/roles'
      path: '/superadmin/roles'
      fullPath: '/superadmin/roles'
      preLoaderRoute: typeof SuperadminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/audit': {
      id: '/superadmin/audit'
      path: '/superadmin/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof SuperadminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshop': {
      id: '/admin/workshop'
      path: '/admin/workshop'
      fullPath: '/admin/workshop'
      preLoaderRoute: typeof AdminWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/admin/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackRouteChildren {
  TrackIdRoute: typeof TrackIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackIdRoute: TrackIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegsiterRoute: RegsiterRoute,
  ServicesRoute: ServicesRoute,
  TrackRoute: TrackRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWorkshopRoute: AdminWorkshopRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  SuperadminAuditRoute: SuperadminAuditRoute,
  SuperadminRolesRoute: SuperadminRolesRoute,
  SuperadminSecurityRoute: SuperadminSecurityRoute,
  AdminIndexRoute: AdminIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
